manifests/init.pp
This fixes unit tests on non-CentOS hosts where the service
name is freeradius instead of radiusd.
=> Rename the Service[radiusd] resource to Service[$fr_service].

manifests/init.pp
`logrotate::rule` expects `rotate` to be a string. This fails with the future parser (Puppet 3) and Puppet 4 otherwise.
=> rotate attribute must be passed as a string

manifests/attr.pp, manifests/client.pp, manifests/init.pp, manifests/ldap.pp, manifests/params.pp, manifests/sql.pp, manifests/statusclient.pp
Make an educated guess about the version of FR when the fact is unavailable (on the first run). Currently this causes problems because `$::freeradius_maj_version` is `undef` on the first run, before the `freeradius` package has been installed.
This change means on the first run, when the fact is undefined, it will make an educated guess about the version of FreeRADIUS by looking at the OS version.
=> Make an educated guess about the version of FR

lib/facter/freeradius_maj_version.rb, lib/facter/freeradius_version.rb
On Debian, the radiusd executable is called freeradius.
=> Look for executable 'freeradius' where 'radiusd' doesn't exist

manifests/ldap.pp, templates/ldap.erb
Write out `ldap.conf` with different syntax for FreeRADIUS 3.0.x and 3.1.x
=> LDAP multiple server fix

manifests/init.pp, manifests/params.pp
Hi there! Thanks for this module.
I've just tried to integrate it into our Puppet 4 Enterprise environment. We have strict variable checking enabled and as such the if statement checking for the presence of this variable errors out. As per this blog post https://blog.yo61.com/test-for-undefined-fact-in-puppet-with-strict_variables/ I was able to overcome this.
Additionally, the version comparison check fails the explicit != so I have replaced with a validate_re which does the trick. There may be a trailing special char or something which now fails on the far more strict Puppet 4 environment.
Both of these rely only on stdlib and I'm fairly sure they should remain compatible with Puppet 3 but the changes have only been tested on 4.
=> Fix compatibility with strict variable checking and version comparison on Puppet 4

manifests/params.pp
I am so sorry!
I thought I had tested this thoroughly but it turns out that on a guessed puppet run(ie before the package is installed) with my validate_re change it crashes out because it tries to compare a string to a fixednum in puppet 4. Turning the guessed versions into a string does fix this.
Many many apologies for the incomplete pull request yesterday, I know this takes your precious time to review.
=> Fix validate_re on guessed fact run

templates/radiusd.logrotate.erb
This takes care of the situation where the daemon isn't running and logrotate tries to rotate the logfiles.  See uob#133
=> test for the existance of the pidfile before trying to HUP the daemon

manifests/params.pp, templates/radiusd.conf.erb
Debian uses /usr/lib/freeradius as libpath. The current puppet module doesn't work with the packages from 1labs. This commit adds a $libdir variable, which is evaluated and used in  `radiusd.conf.erb`.
=> Fix libdir path

manifests/dictionary.pp
This way you could directly use the content or a template to create the
freeradius dictionary
=> Add content parameter to freeradius::dictionary

manifests/init.pp, templates/radiusd.conf.erb
Currently the regex escape sequences of policy.d/filters doesn't work with 1lab packages on jessie. This enables correct_escapes=true in radius.d conf.
The following shipped filter doesn't work, with the shipped puppet configuration:
```
if (&User-Name =~ /\.\./ ) {
...
```
=> Add correct_escapes=true to radiusd.conf

types/integer.pp
This definition uses the defined type Freeradius::Integer, but it was not included in the previous PR.
This type (which could be used in other parameter definitions) is equal to an integer or a string starting with '$' (to be able to use variable references)
=> Fix for freeradius::module::eap

README.md, manifests/ldap.pp, manifests/module/ldap.pp, templates/ldap.erb, types/sasl.pp, types/scope.pp
I have completed the ldap define to be able to configure nearly all possible parameters of the ldap module.
In this reimplementation I have move ```freeradius::ldap``` to ```freeradius::module::ldap``` but maintaining the former with a deprecation warning (and calling the new). I have done this way because I think this _namespace_ is more appropiate than directly in ```freeradius```, but if you don't like I can change it and preserve the original ```freeradius::ldap```.
=> Add a more exhaustive list of parameters to ldap

templates/site.erb
It fails when you use freeradius::site listen parameter
=> Fix template for freeradius::site

manifests/listen.pp
The type Freeradius::Listen_type does not exists. It is an enumerate of
valid listen type
=> Fix freeradius::listen

manifests/params.pp
freeradius init script do have status option in debian systems. Without this modification, freeradius is restarted when a config file is changed, but it not started if it is not running.
=> Fix freeradius service in debian systems

templates/client.conf.erb
When the template is used from freeradius::statusclient there are some
parameteres (require_message_authenticator) that are not set, so this condition
must be considered in the template.
=> Fix client template when used from freeradius::statusclient

manifests/status_server.pp
Although it is declared as mandatory, it is not used anywhere.
=> Remove secret parameter from freeradius::status_server

manifests/params.pp, templates/radiusd.conf.erb
Config created was not correct because in debian based systems
use paths slightly different than others.
=> Fix db_dir option of radiusd.conf in debian systems

manifests/init.pp, manifests/params.pp, templates/radiusd.conf.erb
This PR add two parameters to freeradius class:
1. ```$manage_logpath```: this parameter handle if logpath should be managed with puppet or not. It defaults to true, which correspond to previous behaviour. If set it to false, then ```radacct``` is not directly created/modified by puppet
1. ```$radacctdir```: With this parameter you can configure that path in freeradius. It defaults to ```${logdir}/radacct``` which is the _standard_ path.
=> Add parameters to freeradius class

metadata.json
I was wondering if you would consider updating the logrotate module dependency.
This change would be good given changes for Puppet 4 (and sometime in the near-future Puppet 5).
The `rodjek/logrotate` module hasn't been updated for a number of years.
There is an active fork with fixes and updates applied https://github.com/yo61/puppet-logrotate
This fork also has `Approved` status on the Forge: https://forge.puppet.com/yo61/logrotate
=> Update for logrotate module dependency

manifests/init.pp
I was taking a quick look through your module and you don't appear to manage the `freeradius-postgresql` package required for the SQL module.
This change will start by installing the package required for `freeradius::sql` to use `database` as `postgresql`.
=> Add postgresql support

manifests/attr.pp, manifests/init.pp, manifests/krb5.pp, manifests/module.pp, manifests/module/ldap.pp, manifests/site.pp, manifests/sql.pp
sites:
- deploy files to sites-available and symlink to sites-enabled
modules:
- deploy modules to mod-available and symlink them to `$::freeradius::params::fr_modulepath`
There is further work to do to refactor the paths these files/links are deployed to, as `fr_modulepath` is currently derived from a selector based on the version of freeradius being deployed.
Refactoring references to `fr_modulepath` is a larger change than is required to fix #83, as it changes the interface this module presents to the outside world, and some deployments may be reliant on overriding `fr_modulepath` from outside this module.
=> deploy modules and sites to their respective *-available directory

manifests/krb5.pp
Fix a typo int he module config path for krb5
=> Fix "mods-available" path for Krb5

manifests/module.pp, manifests/site.pp
The link in mods-enabled directory should not be present is module has
`ensure => absent`.
The same applies to `freeradius::site`
=> Fix link in absent modules

manifests/init.pp
I'm implementing some new freeradius setups, and this module seems pretty much exactly what I need, except it fails to run complaining about:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Logrotate::Rule[radacct]: parameter 'rotate' expects a value of type Undef or Integer, got String at /etc/puppetlabs/code/environments/freeradius/modules/freeradius/manifests/init.pp:311 on node radius.ab2.staging.gigaclear.net
```
I made the obvious change as in this pull request, and it seems to fix the problem.  Yet there was
clearly a commit fba271f0ec83362547c4ed193eab0d9df1a8770a in 2015 that made exactly the opposite change, and this problem is such a clear show-stopper I must be missing …
=> Test provinding values as integers

README.md, manifests/init.pp, manifests/params.pp
Update to handle the new directory structure introduced in Debian 9
The DHCP module has been moved to a package, hence the addition of $dhcp_support
Issue #87
=> Debian 9 ( Stretch ) support

templates/eap.erb
Simply enabling the eap module like so:
```
freeradius::module::eap { 'eap':
ensure => 'present',
}
```
results in a broken configuration:
```
...
including configuration file /etc/raddb/mods-enabled/eap
/etc/raddb/mods-enabled/eap[604]: Too many closing braces
Errors reading or parsing /etc/raddb/radiusd.conf
```
Move the opening `gtc {` outside the block that is conditional on the
definition of `@gtc_challenge`
=> Fix unbalanced brackets in the eap module

manifests/sql.pp
$custom_query_file is initialized as undef, so this check implied custom_query_file was always used is sql module does not work if you don't manually configure custom_query_file.
This PR fixes this problem.
=> Fix query_file path

manifests/huntgroup.pp, templates/huntgroup.erb
In huntgroups, when there is more than one condition for a huntgroup, each condition should be indicated in one huntgroup line, instead of separated by commas.
In this PR I have also deleted the huntgroup template that is not needed anymore since PR#96.
=> Fix huntgroups when there is more than one condition

manifests/init.pp
* Permissions for top level directories under `mods-config`
* Manage attr_filter module's default config files so we can set permissions
* Manage the `hints` file so we can set permissions
=> Default permission issues

manifests/realm.pp
When using concat::fragment the fragments gets sorted using both the order attribute and the name. 
There are times you need to have the realms in a specific order and this sorting of fragments disrupts this intended order.
This is fixed in this PR by using adding a modifier parameter. A parameter that modifies the base order used by the fragment.
I used the name realm_order but I'm not that convinced that this is the right name for it. Maybe 'priority' or perhaps plain 'order' is good enough.
=> Add order parameter to realm class

README.md
Replace single quote with backtick to get the table of contents to display cleanly.
=> Minor formatting fixup in README.md

manifests/init.pp
This pull request fixes a problematic situation when the `attr_file` module is enabled after the start of the corresponding service.
You can see the erroneous order in the following snippet.
```
Notice: /Stage[main]/Freeradius/Service[freeradius]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Freeradius/File[/etc/freeradius/3.0/mods-enabled/attr_filter]/ensure: created
```
=> Bugfix: Enable attr_filter module before service's boost

manifests/module/eap.pp, manifests/params.pp, templates/eap.erb
Still in testing (but frozen), on Debian Buster actually the fact 'operatingsystemmajrelease' resolves to 'buster/sid'
=> Next version of Debian is 10

.gitignore, manifests/module.pp
now, if module file is updated, service is not notified since notify is only set on the symlink, which obviously stays the same. So just added notify to base module file
=> module file notifies service, not only symlink

manifests/client.pp
Removed hypens from firewall resources within client.pp to stop iptables rules being repeatedly added by subequent Puppet runs. Fixes #121
=> Fix for client iptables rules being repeatedly added by subsequent Puppet runs

manifests/module/ippool.pp
When defining an `freerad::module::ippool` this declaration also create
needed files.
These files could be created when freeradius starts, but in many cases the freeradius user doesn't have write permissiones in the freeradius directory (that is owned by root).
This patch creates these files from puppet.
=> Create ippool files in freerad::module::ippool

manifests/client.pp, manifests/home_server_pool.pp, manifests/huntgroup.pp, manifests/listen.pp, manifests/sql.pp
* `freeradius::client`:
* `nastype` and `proto` are optional parameters
* `attributes` could also be a hash or a string
* `freeradius::listen`:
* `interface` parameter is optional
* `freeradius::home_server_pool`:
* `home_server` parameter could be an array of strings too
* `freeradius::sql`:
* pool_connect_timeout default value must be a float, not a string
* `freeradius::huntgroup`
* Parameter `order` is used in `concat::fragment` which accepts
strings or integer
=> Fix parameters checks in various definitions:

manifests/init.pp
When `huntgroups` file is updated, a service restart is needed.
=> Restarts freeradius after any huntgroups modification

README.md, manifests/init.pp, spec/classes/freeradius_spec.rb, spec/shared_contexts.rb, templates/radiusd.conf.erb
this change allows to change the parameter max_request_time , which is set to the default value of 30 otherwise without any chance to change it
=> parametrize max_request_time

templates/ldap.erb
In the current LDAP template, `identity` is quoted, but `password` is not.
```erb
<%- if @identity -%>
identity = '<%= @identity %>'
<%- end -%>
<%- if @password -%>
password = <%= @password %>
<%- end -%>
```
This PR makes them both (single) quoted.
=> quote ldap password

README.md, manifests/init.pp, templates/radiusd.conf.erb
We syslog to centralized syslog servers and separate different types of traffic by facility.   This was hardcoded to "daemon", so I added an optional parameter.
=> parameterize syslog_facility

spec/defines/ldap_spec.rb
In 31a05c3 we put quotes around the LDAP password - but did not update the tests. This should sort that out.
=> Add quotes around expected LDAP password in freeradius::ldap spec

manifests/init.pp, spec/classes/freeradius_spec.rb
If this module creates the radius log dirs, the owner and group is 'root' by default - so let's set it to the radius user.
=> Set ownership for radacct and radius log dir

templates/client.conf.erb
In d2885da16c252658e31c17e91bd35df2f044d5d5 I was changing `if @var` to `if defined?(@var)` and accidentally changed:
```ruby
if @attributes.respond_to?('join')
```
to
```ruby
if defined?(@attributes).respond_to?('join')
```
which obviously doesn't work.
This commit reverts that, and doesn't check check `defined?(@attributes)` several times.
=> Fix client attributes so that hashes and arrays work correctly

manifests/client.pp, manifests/home_server.pp, manifests/ldap.pp, manifests/module/eap.pp, manifests/module/ldap.pp, manifests/sql.pp, manifests/statusclient.pp, spec/defines/client_spec.rb, spec/defines/home_server_spec.rb, spec/defines/module/ldap_spec.rb, spec/defines/sql_spec.rb, spec/defines/statusclient_spec.rb, types/password.pp, types/secret.pp
Clients can accept secrets with a newline as part of the string, which causes the RADIUS system to restart and.. fail to start, because the resulting config is something like:
```
secret = "foo
bar"
```
This PR implements a basic check which looks for a negative answer to "is this entire string not `\n` chars", and then raises an error. I've implemented the logic like this so we can add other "illegal" chars easily if we find them.
=> Sanity check secrets in freeradius::client

manifests/dictionary.pp, manifests/init.pp, manifests/policy.pp, spec/classes/freeradius_spec.rb, spec/defines/policy_spec.rb
We currently use `\n` at the end of concat fragments. Concat has an `ensure_newline` parameter which handles this for you, so we don't have to remember to add a newline at the end of each fragment.
This changes updates the concats to use this, and removes the manual `\n` from the end of fragments.
This parameter has been in concat since 1.0.0 so no version requirements change here (currently we require `>=1.0.0 <7.0.0`).
=> Use ensure_newline for concats fragments

README.md, manifests/attr.pp, manifests/listen.pp, spec/defines/attr_spec.rb, templates/attr.erb, templates/listen.erb
Add the 'virtual_server = ...' statement to listeners, for servers with multiple listeners.
Add the 'relaxed = ...' statement to the attribute filter, to allow for pass-through style filtering.
=> Add virtual servers to listeners and add 'relaxed' option to attr_filter

spec/defines/client_spec.rb, spec/defines/home_server_spec.rb, templates/client.conf.erb, templates/eap.erb, templates/home_server.erb
Secrets and passwords should be wrapped in quotes, to avoid issues with unusual chars.
This has been tested in my environment and is working fine.
=> Wrap secrets and passwords in quotes

manifests/params.pp, metadata.json
Add Rocky to the list of Redhat-distributions to allow usage on a freshly installed Rocky-system.
=> add Rocky to list of Redhat-dists

manifests/client.pp, spec/defines/client_spec.rb
- Add Array as an accepted type to `freeradius::client`
- Add testing for the firewall rules defined in `freeradius::client`.
Fixes #136
=> Allow client param $port to be an integer or an array

spec/defines/client_spec.rb
In #160 I added specs for the freeradius::client define, which had a bad typo in them - not closing off the `let(:params)` block. This fixes that so that all tests pass.
=> Fix typo in freeradius::client spec

.github/workflows/publish.yml, .github/workflows/test.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, spec/defines/client_spec.rb
Create a GitHub workflow which runs PDK tests - just using the workflow example from https://github.com/mysociety/action-pdk for now.
This workflow currently fails because of the issue that will be fixed in #174.
Github actions is good - there are other options available, but this is super low effort to make go. If we find it lacking we can look at others - but I think if we look at using GH Actions for doing releases then it's reasonable to use it for testing, too.
=> Add github workflow to run PDK tests

manifests/params.pp, metadata.json
This PR will add support for EL9 and also include AlmaLinux in the process.
Please note that CI is currently failing (which I fixed in PR #181). I can rebase once that other PR got merged.
=> add support for EL9 (RedHat, Rocky and AlmaLinux)

manifests/params.pp, templates/ldap.erb
add version strings for Ubuntu  22.04 and ldap template for update parameter
=> add support for ubuntu 22.04

manifests/init.pp, manifests/module/detail.pp, manifests/sql.pp, manifests/virtual_module.pp, metadata.json
replaces usage of old validation_()-functions with proper type-definition and therefore allows the usage of `puppet-stdlib` 9.0.0.
Bonus: also fixes the CI ;)
=> bump for stdlib 9

spec/defines/module/ldap_spec.rb, templates/ldap.erb
In #173 the ldap template was broken so that the update section header/closing brace is not included if `update` is passed to `freeradius::module::ldap`.
Instead, make the update section always appear, and then the conditional is only on the contents of the section.
Resolves #189
=> Fix ldap config update section

manifests/params.pp
Even though it is FreeRadius 3.2, still the directory "3.0" is used by systemd service
=> Debian 11 support

.devcontainer/Dockerfile
I am on an arm Mac, so have to have this in the Dockerfile to make vscode play nice - as pdk containers only ship for x86_64.
=> Make devcontainer work on non-x86_64

manifests/client.pp, spec/defines/client_spec.rb
Use name instead of shortname in client definition for filename, firewall rule and huntgroup to allow the same shortname for different clients.
In some setups it may be needed that a client must be published multiple times with different ip addresses. In 1.x it was possible since it the client "name" was the IP itself. For 2.x the client "name" is now the `shortname` but there exist no definition that it needs to be uniq as far as we could found.
=> Use name instead of shortname for client definition

.github/workflows/publish.yml, .github/workflows/test.yml
Update to latest versions of the GitHub Actions we rely on, and in some cases specify only the major release so we will track minor versions every run.
If this PR passes its pipeline, it's safe to merge. We won't be able to fully test the `barnumbirr/action-forge-publish` action until we come to publish our next release, but that's a job for another day.
=> Update to latest GitHub Actions

.fixtures.yml, manifests/init.pp, metadata.json, spec/classes/freeradius_spec.rb, templates/systemd_dropin_rhel8.erb
This PR includes the changes by @minorOffense from #178 which was incomplete, and some fixes by @nward from the `144-rocky8` branch.
Supersedes #178 
Fixes #144
=> Rocky 8 support

templates/detail.erb
The locking parameter is a Enum['no', 'yes'], so it can't be checked  neither assigned as a boolean. The assignment must be to the value of the parameter, if present.
=> Fix locking in freeradius::module::detail

manifests/init.pp, templates/trigger.conf.erb
Added a template for trigger.conf and 4 new parameters for freeradius class
- $snmp_traps_enable - Whether to actual trap and not just echo commands
- $snmp_traps_community - The SNMP community string/shared secret of the trap destination
- $snmp_traps_dest - The IP address of the trap destination
- $snmp_traps - And array of trap names, if empty it is populated with all trap names, if a list of traps is supplied then those are enabled.
There are no dependencies between parameters to allow full configuration of file and checking before enabling traps
=> Individual SNMP trap enabling

manifests/listen.pp, metadata.json
Bump the lower bound on stdlib to 5.0.0
=> Remove is_ip_address function removed from stdlib in 9.x

manifests/client.pp, metadata.json, spec/defines/client_spec.rb
The puppetlabs firewall module had some breaking changes in v7. Of interest are the "action" parameter being removed in favour of "jump" and the "provider" parameter being removed to specify ip6tables etc. in favour of "protocol".
This PR updates the module and uses the newer parameters, which will also fix tests on #217 if rebased.
=> Update calls to firewall module

manifests/site.pp, spec/defines/site_spec.rb
The sites-enabled links point to an absolute path, while mods-enabled are relative. This updates sites-enabled links to follow the same pattern.
=> Fix link target for sites-enabled

.github/workflows/publish.yml
Run publish workflow on new GH release, not when tags are pushed
=> Publish on new release only

README.md, manifests/init.pp, manifests/params.pp, metadata.json
There were fixes for this in #199 but that was deferred to discussion of other changes in that PR. This is a short/simple PR that removes the classic facts used in versions of Puppet not supported by this module anyway.
fixes #221
=> Version 4.0.1 fix Puppet 8 compatibility, replace classic facts

manifests/module/ldap.pp, manifests/params.pp
My apologies. I changed a variable name in my last PR, causing this:
```
Evaluation Error: Cannot reassign variable '$fr_service' (file: **modules/freeradius/manifests/params.pp, line: 78, column: 15)
```
There's also an unrelated error where `ldap` is looking for the version fact as an top-level (legacy) fact.
```
Evaluation Error: Unknown variable: '::freeradius_version'. (file: **/modules/freeradius/manifests/module/ldap.pp, line: 77, column: 24)
```
=> Bugfix cannot reassign variable fr_service

manifests/policy.pp
Hi @djjudas21, an environment I'm managing using data from hiera to construct a policy for adding VSAs to responses.  Currently this is done in the sites file using a template, and about 50 lines of if, elsif, and case statements is untidy, so I've added a content option to policy.pp so a template can populate the policy file.
Probably something for Monday, but its working fine in my environment
=> Policy file content option for using templates

manifests/module/ldap.pp, templates/ldap.erb
Hi @djjudas21 
When multi-factor authentication is implemented within an LDAP server, it does not respond until user responds. 
Setting net_timeout to more than 1 second stops FreeRadius timing out waiting, but the default is still 1 second
=> Increasing timeout for response from LDAP server
