djjudas21/puppet-freeradius

- README.md
- manifests/cert.pp
- manifests/config.pp
- templates/radiusd.conf.erb
Makes the modules a bit more flexible...
> Allow for 'content' to be passed into freeradius::config and freeradius::cert

- README.md
- manifests/ldap.pp
- templates/ldap.fr2.erb
- templates/ldap.fr3.erb
Support specifying multiple LDAP servers
> Multiple LDAP servers

- README.md
- manifests/init.pp
- manifests/module.pp
Various changes to preserve stock modules in a FreeRADIUS installation and be able to toggle them
> Preserve modules

- README.md
- manifests/init.pp
- manifests/krb5.pp
- spec/classes/freeradius_spec.rb
- spec/defines/krb5_spec.rb
- spec/shared_contexts.rb
- templates/krb5.erb
I have created this commit to support configuring the krb5 module. It is based on the work I've found adding support for ldap. Let me know if anything is missing or just plain wrong.
> Add support to configure the krb5 module

- README.md
- manifests/init.pp
- templates/radiusd.conf.erb
Adds the option "log_destination" to configure the destination of log
messages.
> Adds option to configure destination of logs

- README.md
- manifests/home_server.pp
- templates/home_server.erb
This way you can configure how the home_server is check if it is
dead or alive
> Add status_check parameter to freeradius::home_server

- README.md
- manifests/client.pp
- templates/client.conf.erb
This parameter is an array of attributes to assign to the defined client.
> Add attributes parameter to freeradius::client

- README.md
- manifests/client.pp
- templates/client.conf.erb
As you suggested I have completed ```freeradius::client``` parameters to include all the options included at [sample config](https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/clients.conf)
> Add exhaustive parameter list to freeradius::client

- manifests/init.pp
- manifests/listen.pp
- templates/listen.erb
- templates/radiusd.conf.erb
This is a way to configure listen directives not directly associated to
any specific virtual server
> Add freeradius::listen to define listen directives

- manifests/client.pp
> Make freeradius::client shortname optional and default to $title

- README.md
- manifests/sql.pp
- templates/sql.conf.erb
The parameters added are to configure connection pool
> Add more parameters to freeradius::sql

- README.md
- manifests/site.pp
- templates/site.erb
Add authorize, authenticate,... parameters to freeradius::site so they
could be used to configure the site.
> Add more parameters to freeradius::site

- manifests/init.pp
> Less strict directory modes for $basedir and subdirectories

- manifests/module/preprocess.pp
- templates/preprocess.erb
> Fix an errata and tabulation of the template

- manifests/module/files.pp
- templates/files.erb
- templates/users.erb
> Add freeradius::module::files

- manifests/sql.pp
- templates/sql.conf.erb
* It was checking parameters with the wrong name
* The database driver was not correctly configured in the template
> Fix freeradius::sql

- manifests/module/files.pp
- templates/files.erb
acctusersfile and preproxy_usersfile should be configured by default as
undef.
> Fix freeradius::module::files

- README.md
> Add missing docs for #109

- manifests/home_server.pp
- templates/home_server.erb
Hello
Quick adjustment to allow for check_timeout option in homeserver configuration.
> Add support for homeserver check_timeout

- manifests/init.pp
- spec/classes/freeradius_spec.rb
These files have the literal characters \n in them rather than a newline - switching '' to "" fixes this
> Fix interpolation - '' -> ""

- templates/client.conf.erb
Correct removal off linebreak introduced in d2885da16c252658e31c17e91bd35df2f044d5d5
> Add linebreak after lifetime attribute

- templates/detail.erb
This should fix the issue https://github.com/djjudas21/puppet-freeradius/issues/171
> Add module name to detail.erb

- templates/ldap.erb
ldap server set to localhost, irrespective of whether you point it at your own server.  And parts of update example not commented out
> ldap module template

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .gitignore
- .gitlab-ci.yml
- .pdkignore
- .travis.yml
- Rakefile
- appveyor.yml
- metadata.json
- spec/spec_helper.rb
Update to the latest PDK version
> Update to PDK 2.4.0

- manifests/params.pp
- metadata.json
I am successfully using this to install FreeradIus on Ubuntu 24 machines
> Ubuntu 24 and systemd puppet compatibility increment
